### ISSUE TITLE
7.1 First Functional Packaging Finished

### ISSUE THREAD

**Issue by BoXunTong** [BoXunTong/Automated_Pet_Feeding#6]
Encapsulate the pump code and add recognition threads with pump callback function tests.

**Comment by BoXunTong** [comment]
Task assigned to YUCHEN ZHI @zyc2333333

**Comment by zyc2333333** [comment]
Copy that

**Comment by Vrachaos** [comment]
The weight sensor still needs to be optimised.

**Comment by Yue2022pro** [comment]
Need to modify the code related to the camera process.

**Comment by zyc2333333** [comment]
Make research on the iteration of the "detect_pet_thread" function

**Comment by BoXunTong** [comment]
Add thread-safe exit code @Vrachaos

**Comment by BoXunTong** [comment]
Add weight sensor code @Yue2022pro
